# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

remote_theme: lgalke/athena@master

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lukas Galke Poech
description: >
  Assistant Professor<br/>
  University of Southern Denmark (SDU)<br/>
  Faculty of Science<br/>
  Department of Mathematics and Computer Science (IMADA)<br/>
  Data Science Section<br/>
  Center for Machine Learning<br/>
  Affiliate member of the Pioneer Centre for Artificial Intelligence (P1)<br/>
mission: >
  My research advances AI safety by investigating how and why the most powerful AI systems behave the way they do.
news:
  - date: "February 2026"
    text: >
      Three papers accepted to LREC2026.
  - date: "November 2025"
    text: >
      The <a href="/projects#mist">MIST project</a> on mechanistic interpretability
      for safe LLM agents has been funded by the Novo Nordisk Foundation.
      I am now hiring at PhD and Postdoc levelâ€”<a href="mailto:lukas@lpag.de">get in touch</a>
      if you're interested.
  - date: "November 2025"
    text: >
      FlexDeMo has been accepted to <a href="https://aaai.org/conference/aaai/aaai-26/">AAAI 2026</a>.
  - date: "October 2025"
    text: >
      <a href="https://aclanthology.org/2025.findings-ijcnlp.45/">Culture Neurons</a> have been accepted to <a href="https://2025.aaclnet.org">AACL-IJCNLP 2025</a> Findings.
# baseurl: "/athena" # the subpath of your site, e.g. /blog
url: "https://lgalke.github.io" # the base hostname & protocol for your site
github_repo: lgalke.github.io # the GitHub repo name for your project
github_username: lgalke

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: LukasGalke

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: light

# Seo
tagline: Tracing connectionist mechanisms for safer AI systems.

# Build settings
markdown: kramdown

include:
  - llms.txt

# Plugins
plugins:
  - jekyll-seo-tag

